travis:
  secure:
    BINSTAR_TOKEN: uLUdQZU3avdXB7LckbBq0V4DxFNCkvPWK2R5558nU8w7qDPmnHFQ98ZhExbH5xeR56vMoT2gJkVYHDngZ3NmOlqH/zKPy4udfItP50dFtP+zwVe8hMpuVevHq488TOq6dUSmcNdtZTQsOo4cMzo11ZEXKl7eTNp3JvhKDJZUQh9aabqyT7NKIpmk9dXpIF046j1GzpFmjnyITgrdOYVCMQgRF0UEHpF5ODCZTCb+XUiFpDiVEwWXELLMqpoPhR4U+NawRCiEJAR6hANH+/yuRNqX/zTeKkJ4lAF+u9LgGDx7YR2ts2vJ6rNwyyJXzclLKAzXSl7e2SxJs0hfNq3BRoRDQyVzK+O0+8UqPqGt3MY/e1a2hiXpDecy51UpPTNsQ+RKydMD4u+3RxNql4B9v7sGs+BC7hQKmVRVhDNP3L1mQrNyQB20oYnMEKwU+gGvvsj6xEXBlZ/tKx+Iooza/EAcZsmarUDO8YzG//Kal/8yRPVGmtlF0VyLvGDYVPB2M/I8AeP2DsKTkLrGC1kUIePZZvpU1NaO07De+wuLhedawy1pwWWxq7n86NcnreVz7/e27h9t+LODGcxtQghQW8inNbD8WbLQ0K0B7smnOrnc8qNmzyBGv+UBWuhMnDJVKVombAyBM8qJC32Htyik2elsKqerTYJnI2EjHExX+N4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
