travis:
  secure:
    BINSTAR_TOKEN: 1BadAc2EL4P6wYZAzcQrNcLq+XYTBEL4xjWoI6ylHYwYgCXF3gl4VW1B0VhRpUO3nZ/u0wg4d3o8C5Q1njO04pFXRZikyeoWUX1djeqnTvTy2RDtCPl0Ug4KH44VXV/mqi1qh1dUfK3k+Mp39O9CQ4sihJ9EaD0HIvmUZ/WeWuVGvywNlmlLa+Kd5MviPVm0dnOfvkJ2RBnJ0YIc4x2OfEbn431UlU8GJsiT5nEx2a6wejG865ND0B385XOWagNTUIKhms0a4veEFMplLrCFwd5+4DOmMscg4CdQYhf5pAUfDXRehC1ye36uTMQnrxNz6SrS5JCqq+byQ7MTCnmZFY70s5RFSiPHNF4ETa7t92kByJiGOEi7KZ+NUCaVyBubPiSfTVz5mT49e3zpPCxBtHIGGI+DUVHU8WK2dLA8ldebPh5AsUazMyikoBYaUEW8WLvngsnunzcC21AczZtB3RdEiXVo6MMr5V92aMyg5W3WT1442ymglsw53v+RlGdy4Lm++4rZQHAsQFMe+ADVUhRxrzfYxgo6SNsKoDt/3JS21VKSYeG+V+Cm0SBB+y7sgwFRZM+VSVsq4/yAtObmh3W/UeYQgj31M8nMyWOqaZwXyTGP8ZbbVvmv3sCt83Z8BI+F8MaVkMILolMZYmb929YQ/0N+nWzgeB89Qvv4fvs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
